package com.eight87.whisperboy.ui.settings

import android.content.Context
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.eight87.whisperboy.R
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * oss-licenses Phase B — Open-source licenses sub-screen. Renders the
 * inventory generated by the Licensee Gradle plugin at build time
 * (`assets/licenses/artifacts.json`). Tapping a row opens a dialog with
 * the canonical SPDX license text shipped at `assets/licenses/<spdx>.txt`.
 *
 * Pure-Compose, no ViewModel — the work is one cheap I/O on the assets
 * folder + a kotlinx.serialization parse, which fits comfortably inside
 * `remember(context) { … }` and keeps the surface a single composable.
 */

@Serializable
private data class LicenseeArtifact(
  val groupId: String,
  val artifactId: String,
  val version: String,
  val name: String? = null,
  val spdxLicenses: List<LicenseeSpdx> = emptyList(),
)

@Serializable
private data class LicenseeSpdx(
  val identifier: String,
  val name: String? = null,
  val url: String? = null,
)

data class LicenseEntry(
  val groupId: String,
  val artifactId: String,
  val version: String,
  val spdxId: String?,
  val licenseText: String?,
)

private val licenseeJson = Json { ignoreUnknownKeys = true }

/**
 * Reads the Licensee inventory + per-SPDX license texts from the APK's
 * `assets/licenses/` folder and folds them into a sorted list of
 * [LicenseEntry]. Returns an empty list on any failure — the screen
 * renders a "couldn't load" message in that case.
 */
internal fun loadLicensesFromAssets(context: Context): List<LicenseEntry> {
  val raw = runCatching {
    context.assets.open("licenses/artifacts.json").bufferedReader().use { it.readText() }
  }.getOrNull() ?: return emptyList()
  val artifacts = runCatching {
    licenseeJson.decodeFromString<List<LicenseeArtifact>>(raw)
  }.getOrNull() ?: return emptyList()

  // Cache license-text reads so each SPDX file is opened at most once.
  val textCache = mutableMapOf<String, String?>()
  fun resolveText(spdx: String?): String? {
    if (spdx == null) return null
    return textCache.getOrPut(spdx) {
      runCatching {
        context.assets.open("licenses/$spdx.txt").bufferedReader().use { it.readText() }
      }.getOrNull()
    }
  }

  return artifacts.map { a ->
    val spdx = a.spdxLicenses.firstOrNull()?.identifier
    LicenseEntry(
      groupId = a.groupId,
      artifactId = a.artifactId,
      version = a.version,
      spdxId = spdx,
      licenseText = resolveText(spdx),
    )
  }.sortedWith(compareBy({ it.groupId }, { it.artifactId }))
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun LicensesScreen(
  onBack: () -> Unit,
  modifier: Modifier = Modifier,
) {
  val context = LocalContext.current
  val entries = remember(context) { loadLicensesFromAssets(context) }
  var expanded by remember { mutableStateOf<LicenseEntry?>(null) }

  Scaffold(
    modifier = modifier,
    topBar = {
      TopAppBar(
        title = { Text(stringResource(R.string.licenses_title)) },
        navigationIcon = {
          IconButton(
            onClick = onBack,
            modifier = Modifier.semantics { testTag = "licenses_back" },
          ) {
            Icon(
              imageVector = Icons.AutoMirrored.Filled.ArrowBack,
              contentDescription = stringResource(R.string.licenses_back_cd),
            )
          }
        },
      )
    },
  ) { innerPadding ->
    if (entries.isEmpty()) {
      Column(
        modifier = Modifier
          .fillMaxSize()
          .padding(innerPadding)
          .padding(horizontal = 16.dp, vertical = 12.dp)
          .semantics { testTag = "licenses_empty" },
      ) {
        Text(
          text = stringResource(R.string.licenses_load_error),
          style = MaterialTheme.typography.bodyMedium,
          color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
      }
      return@Scaffold
    }

    LazyColumn(
      modifier = Modifier
        .fillMaxSize()
        .padding(innerPadding)
        .semantics { testTag = "licenses_screen" },
      contentPadding = PaddingValues(
        start = 16.dp,
        end = 16.dp,
        top = 12.dp,
        bottom = 24.dp,
      ),
      verticalArrangement = Arrangement.spacedBy(8.dp),
    ) {
      items(entries, key = { "${it.groupId}:${it.artifactId}" }) { entry ->
        LicenseCard(entry = entry, onClick = { expanded = entry })
      }
    }
  }

  expanded?.let { entry ->
    AlertDialog(
      onDismissRequest = { expanded = null },
      title = {
        Text("${entry.artifactId} ${entry.version}")
      },
      text = {
        Column(
          modifier = Modifier
            .fillMaxWidth()
            .verticalScroll(rememberScrollState())
            .semantics { testTag = "license_dialog_body" },
        ) {
          Text(
            text = entry.spdxId ?: stringResource(R.string.licenses_unknown_spdx),
            style = MaterialTheme.typography.labelMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
          )
          if (entry.licenseText != null) {
            Spacer(Modifier.height(12.dp))
            Text(
              text = entry.licenseText,
              style = MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace),
            )
          }
        }
      },
      confirmButton = {
        TextButton(onClick = { expanded = null }) {
          Text(stringResource(R.string.licenses_dialog_close))
        }
      },
    )
  }
}

@Composable
private fun LicenseCard(entry: LicenseEntry, onClick: () -> Unit) {
  Card(
    modifier = Modifier.fillMaxWidth(),
    colors = CardDefaults.cardColors(
      containerColor = MaterialTheme.colorScheme.surfaceContainerHigh,
    ),
    elevation = CardDefaults.cardElevation(defaultElevation = 0.dp),
  ) {
    Row(
      modifier = Modifier
        .fillMaxWidth()
        .clickable(onClick = onClick)
        .padding(horizontal = 16.dp, vertical = 12.dp),
      verticalAlignment = Alignment.CenterVertically,
    ) {
      Column(modifier = Modifier.weight(1f)) {
        Text(
          text = "${entry.artifactId} ${entry.version}",
          style = MaterialTheme.typography.bodyLarge,
          fontWeight = FontWeight.Medium,
          color = MaterialTheme.colorScheme.onSurface,
        )
        Spacer(Modifier.height(2.dp))
        Text(
          text = entry.groupId,
          style = MaterialTheme.typography.bodySmall,
          color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
      }
      SpdxBadge(spdxId = entry.spdxId)
    }
  }
}

@Composable
private fun SpdxBadge(spdxId: String?) {
  val label = spdxId ?: stringResource(R.string.licenses_unknown_spdx)
  val badgeCd = stringResource(R.string.licenses_spdx_badge_cd, label)
  Box(
    modifier = Modifier
      .clip(RoundedCornerShape(50))
      .background(MaterialTheme.colorScheme.secondaryContainer)
      .padding(horizontal = 10.dp, vertical = 4.dp)
      .semantics { contentDescription = badgeCd },
  ) {
    Text(
      text = label,
      style = MaterialTheme.typography.labelSmall,
      color = MaterialTheme.colorScheme.onSecondaryContainer,
    )
  }
}
